# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    my_admin_bundle.menu_listener:
        class: AppBundle\EventListener\MenuItemListener
        arguments: ['@security.context']
        tags:
            - { name: kernel.event_listener, event:theme.sidebar_setup_menu, method:onSetupMenu }
    my_admin_bundle.show_user_listener:
        class: AppBundle\EventListener\ShowUserListener
        arguments: ['@security.context']
        tags:
            - { name: kernel.event_listener, event: theme.navbar_user, method: onShowUser }